[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/api/health"
healthcheckTimeout = 120

[variables]
NIXPACKS_NODE_VERSION = "20"
MONGOMS_DISABLE_POSTINSTALL = "1"
